### PR TITLE
upgrade cyclonedx-core-java to 9.x.x

### PR DESCRIPTION
**Pull request by skhokhlov**

### CODE REVIEW

**Comment by skhokhlov** [comment]
Well, from my understanding, the tests are failing because of a bug in cyclonedx-java-core. 
```
CycloneDX: Validating BOM
Unknown keyword meta:enum - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
Unknown keyword deprecated - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
```
https://github.com/CycloneDX/cyclonedx-core-java/blob/master/src/main/resources/bom-1.6.schema.json#L611

That project doesn't have any tests for schema validation

**Comment by skhokhlov** [comment]
Related issue https://github.com/CycloneDX/cyclonedx-core-java/issues/409

**Review by jkowalleck — APPROVED** [review]
LGTM.

adding support for CDX 1.6 ✔️ 
does not change any default values, or does it?

**Comment by jkowalleck** [comment]
@glefloch could you review this PR and maybe merge/release it?

**Comment by skhokhlov** [comment]
> does not change any default values, or does it? if it did, this would be a breaking change ...

just default schema version, will be 1.6

**Comment by VinodAnandan** [comment]
@skhokhlov  can we keep 1.5 as default, maybe we can change the default version in the 1.9.x release?

**Comment by skhokhlov** [comment]
> @skhokhlov can we keep 1.5 as default, maybe we can change the default version in the ~1.9.x~ 2.x release?

Any reason for this? Previously default schema version was update with minor release 1.8.0

**Comment by jkowalleck** [comment]
> > @skhokhlov can we keep 1.5 as default, maybe we can change the default version in the ~1.9.x~ 2.x release?
> 
> Any reason for this? Previously default schema version was update with minor release 1.8.0

Previous changes were non-ideal. They introduced breaking changes without when users did not expect them.
We want to enable users to use CycloneDX 1.6, but don't want to force existing inexperienced users to it. 
The idea is: By not changing the default, we would enable existing users to upgrade easily, without breaking any processes.

**Comment by skhokhlov** [comment]
pushed the change with 1.5 by default

**Review by jkowalleck — APPROVED** [review]

**Comment by skhokhlov** [comment]
Any change to make it merged? 🙃

**Pull request merged**
