### PR TITLE
support for aar dependencies on graph

### LINKED ISSUE #262: AAR files not included on dependency graph
AAR dependencies from android are excluded from the dependency graph, after analysing the code it seems that its forcing only jar files.

### PR DESCRIPTION
**Pull request by fnxpt**
Fixes #262

### CODE REVIEW

**Comment by fnxpt** [comment]
@glefloch

**Review by glefloch — APPROVED** [review]

**Comment by fnxpt** [comment]
@glefloch it looks like the checks failed on the code suggested by lift, are you ok if I'm switch it back to my initial commit?

**Comment by glefloch** [comment]
I think the import of `Object` is missing

**Comment by fnxpt** [comment]
@glefloch can we merge this?

**Comment by glefloch** [comment]
Sure thanks for the contribution

**Pull request merged**
